version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: resume_admin
      POSTGRES_PASSWORD: bharath
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resume_admin -d resume_db"]
      interval: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://resume_admin:bharath@db:5432/resume_db
    ports: ["8000:8000"]
    volumes:
      - ./app:/app/app   # hot-reload edits (optional)
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build: .
    profiles: ["ci"]          # only runs when you call it explicitly
    environment:
      DATABASE_URL: sqlite:///./test.db   # isolated DB for pytest
    command: ["pytest", "-q"]
